CREATE TALBLE IF NOT EXISTS headings
(
    id  INT PRIMARY KEY ALWAYS GENERATED AS IDENTITY,
    number VARCHAR(12) NOT NULL,
    text TEXT NOT NULL,
    tags TEXT NOT NULL,
    count INT NOT NULL DEFAULT 0,
    name TEXT NOT NULL
)